### ISSUE TITLE
In vivo dataset comparisons

### ISSUE THREAD

**Issue by PattF** [theislab/single-cell-tutorial#11]
Hi Malte,

Have a question regarding comparing my dataset to public datasets (~11 sets) from the Allen brain atlas. I'd be interested in being able to "score" my dataset against the in vivo dataset and see how likely it correlates to those datasets. Sort of like an ageing approximation based off how closely it relates to one of the inputted in vivo datasets.
Following the tutorial, lines 38-39 comes to mind where my `rank_genes_groups` for each cluster are compared to the inputted marker genes to look for overlap. Is there a way to do something similar with the described datasets (most of the datasets are gene sets with ~2000 genes each) and plot such correlations with a corresponding score of similarity? I guess it wouldn't necessarily need to be from the `rank_genes` for each cluster but more comparing the system as a whole against the datasets.

Thanks!

**Comment by LuckyMD** [comment]
Hi Patrick,

I think what you're trying to do is a bit out of the scope of the case study to be honest. I wouldn't say it's related to the marker gene overlap calculation. Your case is a bit more complex. You will need to consider what it means that datasets "relate". There are several factors that play into this question:

1. Are you talking about one cell type, or a heterogeneous mixture?
2. Do you have a similar number of cells?
3. Are you comparing two single cell datasets, or are you comparing to bulk?
4. What type of similarity do you care about (that there is a cell type with high similarity, or just all cell types are at least a little similar?)

If they are two single-cell datasets you could pre-process and embed them together and look at either:
- graph-based distances between cells from either dataset
- distances in PCA space (either averages of distances, or distribution metrics like Wasserstein distance)

Overall, I guess I can't really give you a direct answer...

**Comment by PattF** [comment]
Hi Malte,

Thanks for the reply. Sorry, should have added more detail to the question.
The datasets are specific to a brain region (heterogeneous mixture of cell types) that should match in identity to what I've generated in vitro. They are gene sets (top highly expressed genes) from bulk-rna seq data from samples that increase in age from 8pcw to 37pcw. So what I have from each of the in vivo samples are gene sets obtained from allen brain atlas. So its more of a holistic view of how similar do my samples match as a whole to that of the gene sets specific to each of the in vivo samples and which aged sample am I most "similar" to (a heterogenous mixture of cells but specific to a brain region - the same brain region I've generated in vitro). That's why I thought for starters something along the lines of the marker gene overlap calculation, but perhaps looking at the system as a whole rather than individual clusters, and being able to visualise this as a heatmap/matrixplot. Appreciate your feedback if its a feasible (dumb/not dumb) approach.

Thanks!

**Comment by LuckyMD** [comment]
Hi,

So, if all you have is a list of highly expressed genes from the in vivo samples, then I guess you are limited to just comparing lists of highly expressed genes in your single-cell datasets as well. This is assuming you don't have any expression values along with those lists. In that case you can definitely try to use the same overlap approach I am using for the marker gene sets. I'm guessing that you are aware that the gene lists you obtain will heavily depend on the cell type proportions in your sample and not just on the cell types present. So you may have samples looking very similar which share 1 dominant cell type, but no other cell types. A more prudent approach would probably be to use cell cluster marker/highly expressed gene sets, so that you could weight each cell-type similarly (but that assumes you have cell cluster-specific gene expression lists for your in vivo samples as well).
