### ISSUE TITLE
Interpretation of rank_genes_groups

### ISSUE THREAD

**Issue by Lavieenrose123** [theislab/single-cell-tutorial#89]
Hi, 

Thank you providing such a wonderful tutorial!

I'm using _version 1.8.2_ of scanpy and the same code from `Case-study_Mouse-intestinal-epithelium_1906.ipynb`. According to the official tutorial of scanpy, the `scores` in output from `rank_genes_groups` were z-score of `pvals`. If so, a higher score indicate a large p-value. However, the `pvals` in the output of `rank_genes_groups_df` were not monotonically changed while the `scores` were. 

My questions are:

1.  How to calculate `scores`?
2. How to interpret `scores` ？
3. How to obtain negative markers?

Thanks!

**Comment by LuckyMD** [comment]
Hi @Lavieenrose123,

I think this question is better asked in the [scanpy github](www.github.com/theislab/scanpy), rather than here. I'm not sure exactly what the scores are. I think they are probably t-test statistics (if using the t-test via `sc.tl.rank_genes_groups`). In that case higher scores indicate lower p-values.
