### ISSUE TITLE
Batch correction with combat causes Jupyter kernel to die

### ISSUE THREAD

**Issue by barbareyex** [theislab/single-cell-tutorial#96]
I am trying to correct my data with _combat (sc.pp.combat)_. When computing this command in small datasets there's no problem, but when I run it in large anndata files I find troubles because of the memory usage of jupyter notebooks, then the kernel dies. The memory limit is set at 60GB. I tried to change it but didn't find the way. I'm a little stuck with this, so I hope someone have faced this problem and could give me a solution (Not down-sampling because I've already down-sampled my data and what I want to analyze cannot be more down-sampled). Thanks!

**Comment by LuckyMD** [comment]
Hi @RRRReyes,

I'm not aware of a memory limit set by jupyter and I've used jupyter notebooks with more than 60GB of RAM before (on a 384GB RAM server). Maybe this has to do with your system memory limits? I'm afraid I'm not sure how you can reduce memory requirements with a large dataset beyond sparsifying your data matrix and downsampling.

**Comment by epaaso** [comment]
I ran into the same problem and it was indeed due to the memory limits of my system.

To free up some of the memory I avoid saving the log normalized `adata` in `adata.raw` before doing the batch correction, as this doubles the RAM used. Instead I saved the object in an `.hda5` file using `adata.write()` and assigned it to `adata.raw` after the batch correction function as it uses a lot of RAM. You can read the `hda5` file with `sc.read_hda5()`.

Another thing that helped is using the garbage collector of R with `gc()` after running the first R code block.
To get a little bit more of RAM you can also avoid saving the plots in variables.
